var jumoData = [
  {area: "Langa",
  income: 15000,
  householdExpense: {rent: 500,
                     electricity:100,
                     water:100,
                     food: 1000,
                     clothes: 500},

  transportExpense:{petrol: 0,
                    taxi: 100,
                    train: 0,
                    bus:0},

  educationExpense:{primary:500,
                    highschool:0,
                    university:0},

  entertainment:{movies: 25,
                 restuarants: 500,
                 music: 250,
                 sport: 200,
               },
  happy:false,
  sad:true,
  indifferent:false,
  loanAmount: 5000,
  netAmount: 10625,
},

{area: "Nyanga",
income: 10000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 25,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:true,
sad:false,
indifferent:false,
loanAmount: 10000,
},

{area: "Khayelitsha",
income: 5000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 25,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:false,
sad:false,
indifferent:true,
loanAmount: 10000,
},

{area: "Bontehuewel",
income: 15000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 250,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:false,
sad:false,
indifferent:true,
loanAmount: 10000,
},

{area: "Khayelitsha",
income: 5000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 25,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:false,
sad: true,
indifferent:false,
loanAmount: 10000,
},

{area: "Bontehuewel",
income: 6000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 250,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:false,
sad:true,
indifferent:false,
loanAmount: 10000,
},
{area: "Khayelitsha",
income: 5000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 25,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:false,
sad:true,
indifferent:false,
loanAmount: 10000,
},

{area: "Bontehuewel",
income: 4000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 250,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:true,
sad:false,
indifferent:false,
loanAmount: 10000,
},
{area: "Langa",
income: 5000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 25,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:false,
sad:true,
indifferent:false,
loanAmount: 10000,
},

{area: "Bontehuewel",
income: 3000,
householdExpense: {rent: 2500,
                   electricity:500,
                   water:100,
                   food: 1000,
                   clothes: 500},

transportExpense:{petrol:1000,
                  taxi: 100,
                  train: 0,
                  bus:0},

educationExpense:{primary:500,
                  highschool: 1000,
                  university:2000},

entertainment:{movies: 250,
               restuarants: 500,
               music: 250,
               sport: 200,
             },
happy:true,
sad:false,
indifferent:false,
}

];
